routes:
  - path: "/"
    template: "home"
  - path: "/data"
    template: "data-dashboard"

templates: 
  - "home"
  - "data-dashboard"

template_data:
  - name: "home"
    data:
      title: "Home"
      hero_text: "Welcome to the best website ever"
  - name: "data-dashboard"
    data:
      chart_type: "line"
      data_source: "analytics_db"

middlewares:
  - "logger"