routes:
  - path: "/"
    template: "home"
  - path: "/data"
    template: "data-dashboard"
  - path: "/videos"
    template: "video-list"
  - path: "/yo"
    template: "greeting"
  - path: "/sandro"
    template: "profile"

templates: 
  - "home"
  - "data-dashboard"
  - "video-list"
  - "greeting"
  - "profile"
  - "default"

middlewares:
  - "logger"